### ISSUE TITLE
Add a shortcut for the bright display

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Flashlight#109]

**Comment by smarquespt** [comment]
@tibbi I want to update pt language but I can't undestand what is this for. Can you help me?

**Comment by tibbi** [comment]
if you have Android 8+ just long press the app launcher icon, it will show up some shortcuts to some actions. With this Bright Display you can press an shortcut icon on the home screen to directly go into the bright display screen, without launching the app the casual way.

**Comment by smarquespt** [comment]
I've found but I really don't know how to call it. Leaving as is. Thanks

**Comment by tibbi** [comment]
well it is a bright display, not much to not know there :)
