### ISSUE TITLE
Please add bright display quick settings tile

### ISSUE THREAD

**Issue by leaumar** [SimpleMobileTools/Simple-Flashlight#123]
Like the title says, please add a quick setting for bright display, to accompany the one for the regular flashlight. Right now my UX is split between the native (or app's) quick tile for regular flashlight, and the launcher shortcut (a concept I'm not used to using for anything anyway) for bright display.

I tried making my own tile for it with Automate, but [start app](https://llamalab.com/automate/doc/block/activity_start.html) throws a security exception and [start shortcut](https://llamalab.com/automate/doc/block/shortcut_start.html) doesn't list the bright display activity.

Thanks

**Comment by tibbi** [comment]
shortcut has already been there for ages, a Bright display widget has just been added in 5.3.0. Not sure if it is possible to launch a screen with a quick settings tile, will see.

**Comment by leaumar** [comment]
Myeah, I try not to have app/action shortcuts on my home screen, that space is for info widgets. Actions/toggles go in the tiles, apps in the drawer.

Automate can bring up arbitrary screen activities from a quick settings tile, so it must be doable at least. If you could unlock the bright display for external activation (see the doc I linked earlier for activation conditions), that would suffice for me at least, though not for most people of course.
