### ISSUE TITLE
Can't install 5.4.1 on Samsung Note 4 

### ISSUE THREAD

**Issue by theoasispc** [SimpleMobileTools/Simple-Flashlight#130]
It might be because "CPU Architecture: 32-bit"
 
- CPU Quad-core 2.7 GHz Krait 450 - Snapdragon 805
- GPU Adreno 420 (Snapdragon 805)
- OS 6.0.1 (Marshmallow)

**Comment by tibbi** [comment]
Are you getting some error, or what happens? Are you installing it from Google Play, or some other source? I dont think it will be an apps issue.

**Comment by theoasispc** [comment]
Installing it from the .apk there on github and get "App not installed" when I try to install the .apk

**Comment by tibbi** [comment]
try uninstalling it first, just to unstuck it.

**Comment by theoasispc** [comment]
Thanks It worked. :)
