### ISSUE TITLE
Regional language switcher

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [SimpleMobileTools/Simple-Flashlight#143]
In the UK, we don't use the word flashlight, instead we use the word torch. The system flashlight is displayed as "torch" when the language is set to EN_GB, it would be good if Simple Flashlight would respect the system language too.
![img](https://user-images.githubusercontent.com/76442625/156539560-c5066029-8ed1-4b4f-aa7e-f8c7c08ce803.png)
Thank you.

**Comment by tibbi** [comment]
I dont think it is country related, could be your area only

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Hi, this is due to the Android system language being set to EN_GB.
