### ISSUE TITLE
Feature request: Add option to save custom screen colors

### ISSUE THREAD

**Issue by aberkl** [SimpleMobileTools/Simple-Flashlight#167]
Wenn using the phone's display as light source (bright display), I would love to have an option to store several custom colors (tints).

Per default they should be named like #ff0000 with  an option to rename to i.e. "pure Red" or "Tungsten warm".

**Comment by aberkl** [comment]
Fürther Note: It might be a good Idea to display the "Name" on the Screen like "Change colors" right now.

**Comment by tibbi** [comment]
that isnt on the roadmap, you already have stored 5 recent colors

**Comment by aberkl** [comment]
> that isnt on the roadmap, you already have stored 5 recent colors
Whoops! Did not find It, where is It? I am on Version 5.7.0.

**Comment by aberkl** [comment]
Disregard my comment, It ist the 5 bullets. Thanks!
