### ISSUE TITLE
SOS flash needs a noticable pause between S, O and S

### ISSUE THREAD

**Issue by aberkl** [SimpleMobileTools/Simple-Flashlight#168]
See summary, morse code requires a noticable "break" between characters to be "readable".

**Comment by tibbi** [comment]
what summary?

**Comment by aberkl** [comment]
> what summary?
I meant the headline: SOS flash needs a noticable pause between S, O and S

**Comment by tibbi** [comment]
has been fixed in 5.8.4 already
