### ISSUE TITLE
request: add an exit button at the buttom

### ISSUE THREAD

**Issue by finscn** [SimpleMobileTools/Simple-Flashlight#181]
When I use one hand for holding my big phone， i hope i could close app and turn off flashlight by my thumb 。

so i hope there could be an exit button at the buttom of main screen。
and there could be an option to deside wether display it。

**Comment by tibbi** [comment]
there is a Back button at the bottom navigation already..

**Comment by finscn** [comment]
> 

where is it？ I can find it. is it in next release veraion？

**Comment by tibbi** [comment]
at the navigation bar, where in every app... There should be no custom exit button in the app.

**Comment by finscn** [comment]
> at the navigation bar, where in every app... There should be no custom exit button in the app.

the full-screen android no navigation bar.
I know I could use  gesture (e.g. slide screen )  to  'back to home' .
 but the app progress is not be killed. it's just enter the background.
