### ISSUE TITLE
Resources occupied after closing this app properly and openning another app

### ISSUE THREAD

**Issue by Dthird** [SimpleMobileTools/Simple-Flashlight#19]
### Steps to trigger the problem 
1. open the Flashlight app.
2. click the button to let flashlight on and reclick the button to let the flashlight off in order.
3. click the HOME button and open an app which using the flashlight resources(e.g. Camera).
### What happens when you follow the steps
The app open in **Step 3** will report errors or be hanging. Below is a screenshot:
![s61116-094106](https://cloud.githubusercontent.com/assets/4209365/20331935/93c2a29e-abe3-11e6-86ed-c259087afc81.jpg)
### Bugs behind the problem
It does not release the flashlight or relevant services in a proper way.
### The version of the software being used
**Version 1.20** - Added on 2016-09-27
### Environments
* Device: m2 note
* Android version: 5.1

**Comment by srbhmshr344** [comment]
i have done the testing with moto g3 (Android 6)its working fine.

**Comment by tibbi** [comment]
Everything around cameras works so much differently per Android version and manufacturer, that I just cannot fix some of the bugs without having a device with the particular issue :/

**Comment by Dthird** [comment]
Not only the around cameras will trigger this error, but also other flashlight apps(like **Camera** your team developed, **Open Flashlight**, **Search Light**, etc. in [F-Droid](https://f-droid.org/repository/browse/?fdfilter=flashlight&fdpage=1&page_id=0)) will cause similar problem. You can use these apps in the **Step3** for further testing.

**Comment by avipars** [comment]
I had a similar issue, using your app and then a 3rd party flashlight app. I understand that android is a pain in the ass and I blame the other party's app for this.

**Comment by trubitsyn** [comment]
Cannot reproduce this on HTC running Android 6.

**Comment by avipars** [comment]
Try downloading one of the popular flashlight apps on the market and then install and try to use this app. Then you should get this problem. 

I couldn't reproduce it form my friend's device as well.

**Comment by trubitsyn** [comment]
Yes, I get this. Sometimes it reproduces sometimes not.
