### ISSUE TITLE
Requesting adding a toggle for enabling immersive mode in BrightDisplayActivity

### ISSUE THREAD

**Issue by ArchieMeng** [SimpleMobileTools/Simple-Flashlight#199]
I found that showing a navigation bar in BrightDisplayActivity is quite annoying. So, I just implemented this feature by myself. And I wonder if this project will accept this new feature.

This is how it will look like before & after immersive mode enabled:
![Screenshot_20230613-225920_Flashlight_debug](https://github.com/SimpleMobileTools/General-Discussion/assets/12139431/7f0f41b2-adc7-4964-85b9-cc184336e27a)
![Screenshot_20230613-225932_Flashlight_debug](https://github.com/SimpleMobileTools/General-Discussion/assets/12139431/996a07f5-4f2f-4bdc-8755-d508e83c3264)

**Comment by tibbi** [comment]
that isnt really on the roadmap, would be difficult to exit
