### ISSUE TITLE
Strobe not working on devices with android version 6.0 and 6.0.1

### ISSUE THREAD

**Issue by sarevd** [SimpleMobileTools/Simple-Flashlight#24]
The strobe light is not working on samsung,lg and xiaomi phones.

**Comment by sarevd** [comment]
Found a solution.
![image](https://cloud.githubusercontent.com/assets/6833365/22740468/26ae5f94-ee10-11e6-8bf7-77c0ec37719f.png)

**Comment by sarevd** [comment]
That's required by the API for preview to operate, though many devices unfortunately don't enforce this (which is a problem when you then run your app on a strict device).

**Comment by tibbi** [comment]
Hey nice, I will check it out soon. I was also testing it on a couple devices from android 4 to 7, but the current version works on all of them :) Some things are done soo differently depending on the manufacturer and OS version, thats why my Camera app sucks too. Some issues I just cannot reproduce.

**Comment by sarevd** [comment]
For example all the xiaomi phones on 6.0 and 6.0.1 work fine, samsung s5 and lg g4 dont work...

**Comment by tibbi** [comment]
ok Ive applied it, looks like it didnt break anything on my devices, so hopefully it fixes some :) Thanks
