### ISSUE TITLE
F-Droid version

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Flashlight#25]
Hi! The F-Droid version is stop to 1.21 from 27/11/2016. Is possible update it??

**Comment by tibbi** [comment]
They are updating it themselves with a script, not sure why it stopped. Ill check it someday.

**Comment by AlfaOmega33** [comment]
Ok, thank you!

**Comment by tibbi** [comment]
f-droid is messed up now, I will update all apps when it works already
