### ISSUE TITLE
Quick Settings Tile for Simple Flashlight

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Flashlight#31]
My stock flashlight app has a tile in the Quick Settings. I just wanted to replace the app with Simple Flashlight, but there's no tile for it, which makes it a little bit inconvenient to use.
[According to this document](https://developer.android.com/about/versions/nougat/android-7.0.html#tile_api), an app developer can add a tile for his app. Would you implement this feature?

**Comment by chrjsorg** [comment]
The implementation is very easy. I pushed it on my fork and it works so far. I just need to check which icons I can use.

**Comment by tibbi** [comment]
I havent even checked it, guess you can use the img_widget_preview. Even tho it doesnt look like a flashlight, those circles are used at the launcher, in the app and on the widgets too. I will change it once Ill be redesigning the apps. Thanks

**Comment by morfikov** [comment]
I could test it on my phones, but I don't know how to build the .apk file. Is there an easy way to do it?

**Comment by morfikov** [comment]
I just got the update in Google Play, and it looks like the tile works nice on my phone (Android 7.0) :)

**Comment by tibbi** [comment]
okay cool :) I tested it on my devices too, seemed to work just fine.
