### ISSUE TITLE
Add an option for flashing SOS code

### ISSUE THREAD

**Issue by alpenblauwtje** [SimpleMobileTools/Simple-Flashlight#35]
Feature request in the category 'must have': add an option to flash SOS code. Most android flashlight apps have this option. This might save lives.

At the same time you might reconsider the current flash icon, which looks like a spinning wheel. This is IMHO not very intuitive, you might consider a flash icon, like in Asus Flashlight:

![image](https://user-images.githubusercontent.com/7025886/32690030-a2b166be-c6ef-11e7-92df-d55eb56be40a.png)

**Comment by Phoenix1747** [comment]
Yeah, the circle icon is somewhat unfamiliar/confusing at first.

Oh and the SOS blink feature would be quite sweet!

**Comment by MartinGSch** [comment]
I don't find this an appropriate feature for the Simple Flashlight.
Of course, in theory it may save lives and who wants to debate that this is a bad thing... but it is also a very rarely used, specific feature. If you start with that you could certainly also build in several other details like that. And then the apps would not be simple anymore as they are meant to be.
Btw, same for the idea to implement morse codes.

**Comment by MartinGSch** [comment]
There is a separate issue recorded here, about morse codes. That's why I came to that, but just as a "btw" here, let's better not mix up different topics in the same thread.

**Comment by alpenblauwtje** [comment]
The lack of an SOS code and the strange icons within this app are the only reasons I haven't replaced ASUS flash light with this app.

**Comment by tibbi** [comment]
an initial implementation of SOS will be added in 5.0.3 released now
