### ISSUE TITLE
Delay in Flashlight Activation after Turning Off Stroboscope

### ISSUE THREAD

**Issue by thewizardstudio** [SimpleMobileTools/Simple-Flashlight#51]
#### Expected Behavior
Turning off the Stoboscope and then turning on the Flashlight causes the light to activate instantly.

#### Actual Behavior
Turning off the Stoboscope and then turning on the Flashlight causes the light to be delayed in activating.

#### How to Reproduce
1. Launch Simple Flashlight 3.1.0 on Android 8.1
2. Tap the Stroboscope icon
3. Drag the slider all the way to the left
4. Tap the Stroboscope icon immediately after the light flashes off
5. Tap the Flashlight icon

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.1.0
---

#### Recording of the Bug
![FlashOffDelay.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517932838/q42lhqtf72p0wuisvruu.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/delay-in-flashlight-activation-after-turning-off-stroboscope">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
it is related to camera opening/closing, not much I can do about it
