### ISSUE TITLE
New logo design for Simple Flashlight

### ISSUE THREAD

**Issue by sametceylan** [SimpleMobileTools/Simple-Flashlight#62]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for Simple Flashlight. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by tibbi** [comment]
Hey, thanks, but currently Im not looking for a new logo.
