### ISSUE TITLE
Can't able to open Camera when widget in use

### ISSUE THREAD

**Issue by kalaivanan97** [SimpleMobileTools/Simple-Flashlight#7]
I tried this app. Its working pretty well. But I faced a issue when I am trying to use. When the widget is using, I can't able to run camera. It's getting existed.

**Comment by tibbi** [comment]
Hello, I cannot seem to reproduce it. What android version do you have?

**Comment by kalaivanan97** [comment]
Android Lollipop 5.0

**Comment by tibbi** [comment]
can you retest with 1.19 please?

**Comment by trubitsyn** [comment]
@tibbi I'm unable to reproduce this with 1.22.

**Comment by trubitsyn** [comment]
I think #19 is the root of the problem.
