### ISSUE TITLE
I believe "Turn flashlight on at startup" needs a tweak

### ISSUE THREAD

**Issue by MartinGSch** [SimpleMobileTools/Simple-Flashlight#71]
I have activated the setting "turn flashlight on at startup", because that's just how I want to use the app.
Then the following happened:
- After switching the flashlight off I changed to other apps by using the home button (btw, logical as the app has no "switch" to turn the flashlight off and also close the app).
- Later I wanted to use it again, returned to the app by tapping the app icon again. And the flashlight was not turned on... I guess because that was not a 'startup', the app just came to the front again after running in the background.
- But for me it was like "taking a flashlight out of my pocket again", I guess whoever enables this option wants the flashlight to turn on whenever you tap the app icon and bring it to the front.

Small addition: You may also consider evolving this feature by an option "Automatically switch off the flashlight when the app is sent to the background". Or alternatively adding a switch "turn off the flashlight and close the app". Not sure what is the best way - the idea is to save a tap, i.e. turning off the flashlight and go back to home screen with one tap instead of two. 

All this is about nitty gritty details, I know... but being diligent on user experience and simplicity is a design objective for these and app and there I believe such small details matter and many such details make the apps superior.

**Comment by WPFilmmaker** [comment]
+1 I absolutely agree

**Comment by Dejvino** [comment]
Seems to be fixed already.
