### ISSUE TITLE
app asking for additional permissions

### ISSUE THREAD

**Issue by bidaian** [SimpleMobileTools/Simple-Flashlight#72]
X-Privacy warns that Simple-Flashlight wants to access device identification information, the files on the sd card (every time I turn it on) and IPC. There are explicit permissions for those, but they are not listed for the application.

Does anybody know where can I find in the source code the parts that trigger those accesses? I got the apk from F-droid.

**Comment by tibbi** [comment]
nope, Simple Flashlight doesnt require any of those. Those privacy concerned apps are usually broken themselves.
