### ISSUE TITLE
Replace the non-intuitive icons in the app

### ISSUE THREAD

**Issue by alpenblauwtje** [SimpleMobileTools/Simple-Flashlight#73]
Especially the icons for switching the flashlight and the blinking feature are quite non-intuitive. A user has to try them out to see what they do. 
And hopefully there will be a button for an SOS code in the near future too ...

**Comment by breversa** [comment]
Regarding your SOS code : https://github.com/SimpleMobileTools/Simple-Flashlight/issues/77

**Comment by tibbi** [comment]
will be replaced in 5.1.0
