### ISSUE TITLE
[Feature request] Viewfinder

### ISSUE THREAD

**Issue by breversa** [SimpleMobileTools/Simple-Flashlight#76]
Flashlight apps come a dime a dozen, but for years, I've been using Search Light (https://github.com/scottamain/Search_Light) for its unique, never-seen-elsewhere feature : the viewfinder !
It simply displays on the screen what the camera sees... with the light on, of course.

Ever needed to look for an item that fell and rolled under the couch but had to lie on the ground ? Tried to look into a dark, cramped opening in an engine/computer case/human throat, and had to choose between shining some light in there OR actually looking into it ? Well with a viewfinder, you could kiss goodbye to those problems. :-)

As Search Light's development has pretty much stopped, why not import that feature into Simple Flashlight ?

**Comment by tibbi** [comment]
I guess you could just use a Camera with flashlight enabled. Thanks though
