### ISSUE TITLE
[Feature request] Stroboscope/blinking/Morse modes

### ISSUE THREAD

**Issue by breversa** [SimpleMobileTools/Simple-Flashlight#77]
Several features that could make this app even more useful :

1. **Stroboscope mode**, for your cheap, improvised dance parties whereever you are, with optional frequency adjustment knob. Might also help in a self-defense situation to dazzle an aggressor (would that work on animals ?).

2. **Blinking mode** : hiking in the night along a country/forest road ? Strap your device on your backpack, facing back, and warn drivers coming your way to mind your presence. With optional frequency adjustment knob (yep, I know it's the same as stroboscope mode, just with a much lower frequency. Frequency presets may be the best solution).

3. **SOS/Morse mode** : lost during your trip and need to signal for help ? Switch to this mode to flash the standard SOS (. . . - - - . . .) signal. Alternatively, tap the screen to flash the light and send your own Morse messages if you know the code yourself.

4. **Morse-composer mode** : this feature clearly exceeds Simple Flashlight's initial purpose, but why not include a Morse-composer mode ? Type in a text, it then gets converted into Morse code (example library : https://github.com/alwindoss/morse), then flashed (at a given frequency). Only useful if both you and your recipient know Morse code, of course.

OPTIONAL :
Make all features available to flashless devices (e.g. cheap tablets or repurposed phones) by using a max-brightness, white screen (à la MrWhite : https://bc-bd.org/blog/mrwhite.html).

NB :
This FR is a duplicate of https://github.com/scottamain/Search_Light/issues/2

**Comment by tibbi** [comment]
stroboscope and blinking are the same, frequency is good enough for both of them. SOS and Morse are already reported.
