### ISSUE TITLE
Led is noticeably dimmer than stock app

### ISSUE THREAD

**Issue by Mhowser** [SimpleMobileTools/Simple-Flashlight#82]
I can turn on the rear led flashlight using the stock app that came with the phone, and it will be at full brightness. When I switch over to your app there is a noticeable drop in output of light.

The stock app has no brightness changing feature, just on/off and sos.

My phone is the BLU Vivo 5R running nougat 7.0

**Comment by Mhowser** [comment]
Any progress on this bug?

**Comment by tibbi** [comment]
no, how do other downloaded flashlight apps work? Dim, or not?

**Comment by Mhowser** [comment]
Which apps do you rec

**Comment by Mhowser** [comment]
My finger slipped lol

**Comment by tibbi** [comment]
I dont know, just search for Flashlight and try some popular ones

**Comment by tibbi** [comment]
preinstalled apps might be able to change the brightness, but casual downloaded ones cannot. They can only be turned on or off.
