### ISSUE TITLE
Some dependencies can be updated

### ISSUE THREAD

**Issue by TacoTheDank** [SimpleMobileTools/Simple-Flashlight#83]
Android Studio
Your version: 3.2.1
Current version: 3.3.1

Kotlin
Your version: 1.2.71
Current version: 1.3.21

Gradle
https://github.com/gradle/gradle/releases
https://docs.gradle.org/5.1/userguide/upgrading_version_4.html
Your version: 4.6
Current version: 5.2.1

(I'm sure you're aware of this one, but I'll put it down because why not)
```com.simplemobiletools:commons```
Your version: 5.0.14
Current version: 5.9.5

```androidx.constraintlayout:constraintlayout```
Your version: 2.0.0-alpha2
Current version: 2.0.0-alpha3

**IMPORTANT**
```com.squareup:otto``` is deprecated in favor of RxJava

**Comment by tibbi** [comment]
stop with those useles issues and pull requests already. Thanks
