### ISSUE TITLE
[Feature request] Stroboscope: increase maximum frequency

### ISSUE THREAD

**Issue by estearg** [SimpleMobileTools/Simple-Flashlight#86]
Hello,

I'd like to know if it's technically possible to increase the strobe maximum frequency (i.e., decrease MIN_STROBO_DELAY, which is now set to 30 in SimpleActivity.)

Regards,

Esteban

**Comment by tibbi** [comment]
it should be possible, but on some devices it might not work properly

**Comment by estearg** [comment]
Thank you very much.

2019-06-04 4:16 GMT-03:00, Tibor Kaputa <notifications@github.com>:

**Comment by tibbi** [comment]
it has been changed to 10 in june, should be enough I guess
